apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  namespace: web-app01
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/pv0001/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "pv0001-pv-claim"
  namespace: web-app01
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"    

## kubectl exec -it mysql-6978f9689d-h2jc7 -n web-app01 -- /bin/bash      